name: Biological Inspired Design
markdown: redcarpet
pygments: true

# Modify these values
#  url: http://localhost:4000
url: http://tonyfast.com
# Repository Name
baseurl: /Biological-Inspired-Design
# default image location
imgbase: /assets

